name: default
root: ~/
on_project_start: ./bin/start_mopidy.sh
on_project_exit: killall mopidy
windows:
  - player: ncmpcpp
      # layout: 20a0,274x83,0,0{137x83,0,0,3,136x83,138,0[136x41,138,0,5,136x41,138,42,6]}
      # panes:
      # - ncmpcpp:
          # - clear
          # - ./bin/start_mopidy.sh
          # - clear && emacs -nw
  - chat: weechat

